### ISSUE TITLE
Quickly going through inspector or methods in browser hang jade with call to server

### ISSUE THREAD

**Issue by alexkogan** [jgfoster/Jade.bak#245] opened 2020-01-30 18:35 UTC
Unable to exit jade at that stage. Hangs forever. Have to use Task Manager to kill.

![image](https://user-images.githubusercontent.com/1958382/73479086-1ceb9c80-434c-11ea-8efc-3c113c696422.png)

**Comment by obi068** [comment] 2020-04-08 09:43
Yes this is the most annoying bug in Jade.
It think this could happen everywhere during a gemstone call.
Sometimes every few minutes.

![Screenshot_27](https://user-images.githubusercontent.com/1876280/78769815-19991080-798e-11ea-8c1b-a2ca4649ff37.png)

**Comment by feldti** [comment] 2020-04-17 07:41
Yes, I've found this error too. It suddenly pops up while browsing the classes. The only way is to kill the process and start again - sometimes very often

**Comment by jgfoster** [comment] 2020-04-17 14:10
Just a note to let you know that I'm following your reports and this is my top priority for Jade (which, unfortunately, is not my top priority overall, so that's not saying much!). While I've seen something similar, it is sufficiently rare for me that I'm not noticed a pattern. I've attempted to reproduce it in a variety of ways in my environment and haven't had success yet. 

If you are inclined to help diagnose this, any details might help.
 
- Is it recent? If you revert to a version of Jade from long ago does it still happen? 
- Is it influenced by user action? Alex mentioned "quickly" going through methods in a browser. Is that consistently a factor?
- Is it influenced by network or server performance? At the bottom of the browser I believe it shows network and server time for each action. Do you observe a difference between servers that are remote and those that are local?

Presumably this is some sort of race condition so maybe it will only be solved by code analysis  and redesign of the GS call layer.

Anyway, thanks for your reports and your patience. I'm not ignoring you!

**Comment by obi068** [comment] 2020-04-19 13:19
1) I am pretty sure that this doesn't happen with older Jade versions (at least 1 year ago)
2) We are only working with remote servers.
3) I think it does happen more often if you click very fast
4) I also wasn't able to reproduce it, tried many ways, but its really random

**Comment by feldti** [comment] 2020-04-21 07:02
I work with Jade within VirtualBox against my local machine Gemstone/S server and this morning it happened very often and I lost source code several times because I forgot to commit.

I am also sure, that it happened not with older versions of Jade ... but on the other hand I now also work more with newer Gemstone/S version (3.5.x).

This morning it happened when I switched into the Hierarchy view mode (of classes)  and had to go into a deeper hierarchy with 2 classes very fast.

**Comment by thelliez** [comment] 2020-04-30 19:40
I would report the same as obi068.  I have not been able to find a pattern.

It makes it very annoying tome as I have to kill Jade and I lose all the session info from the Jade Login panel (reported as a sparate issue).

**Comment by brunobuzzi** [comment] 2020-05-01 21:25
This does not happen to me but one of the latest feature was:
https://github.com/jgfoster/Jade/issues/240

Not sure if this is the cause of the problem but this can be configurable. As soon as i can will put this feature configurable and disable by default and see if the culprit.

**Comment by jgfoster** [comment] 2020-05-03 08:35
I've changed the way the WaitOnGemStoneDialog is handled so that it does go away if there is a walkback during a GemStone call (see #252). I don't believe that this is exactly the same issue, but if you move to Jade 2.3.15 and the problem goes away, that would be nice to hear!

**Comment by obi068** [comment] 2020-05-07 08:55
Still the same issues with the new version.
In some cases i get also two waiting dialogs.
![image](https://user-images.githubusercontent.com/1876280/81274805-18bcd280-9051-11ea-8ec5-71097d97a00f.png)

**Comment by jgfoster** [comment] 2020-06-23 22:55
Fixed by 52debd5b029dd3056e94846e94818dc3710f3e2f. The Wait dialog is gone and in its place is a GCI Activity tab in the JadeLoginShell. From this window you can interrupt a GCI call and enable a disabled window. While not a major refactoring, it is not trivial and seems to me to be an improvement. Let me know what you find (and, as always, be prepared to revert to an earlier version of Jade if this doesn't work!).

**Closed as completed by jgfoster** 2020-06-23 22:55 UTC
