### ISSUE TITLE
SciLexer error

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#167] opened 2018-07-19 05:06 UTC
V2.2.3, GemStone V3.4.0
Happens sometime if i double click a method in the code editor.

************************** Dolphin Virtual Machine Dump Report ***************************

07:02:20, 19.07.2018: Invalid access to memory location. Reading 0x0, IP 0x55D43412 (C:\Tools\Jade\bin\SciLexer.dll)

*----> VM Context <----*
Process: {00930210:size 421 words, suspended frame 00930791, priority 5, callbacks 2
last failure 2:nil, FP control 80007, thread 00000000}
Active Method: SessionManager>>logError:
IP: 02484EC9 (9)
SP: 00930984
BP: 00930958 (451)
ActiveFrame: {0093095C: cf 0093093D, sp 00930974, bp 00930958, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a GPFault

New Method: VMLibrary>>dump:path:stackDepth:walkbackDepth:
Message Selector: dump:path:stackDepth:walkbackDepth:

*----> Stack Back Trace <----*
{0093095C: cf 0093093D, sp 00930974, bp 00930958, ip 5, JadeSessionManager(SessionManager)>>logError:}
	receiver: a JadeSessionManager
	arg[0]: a GPFault

{0093093C: cf 0093091D, sp 00930950, bp 00930938, ip 3, JadeSessionManager(SessionManager)>>unhandledException:}
	receiver: a JadeSessionManager
	arg[0]: a GPFault

{0093091C: cf 009308FD, sp 00930930, bp 00930918, ip 3, JadeSessionManager(SessionManager)>>onUnhandledError:}
	receiver: a JadeSessionManager
	arg[0]: a GPFault

{009308FC: cf 009308E1, sp 00930910, bp 009308FC, ip 5, GPFault(Error)>>defaultAction}
	receiver: a GPFault

{009308E0: cf 009308AD, sp 009308F4, bp 009308C8, ip 55, GPFault(Exception)>>_propagateFrom:}
	receiver: a GPFault
	arg[0]: a ExceptionHandler
	stack temp[0]: nil
	stack temp[1]: a ExceptionHandler
	stack temp[2]: nil
	stack temp[3]: a Process('Main' base 00930000* in SessionManager>>logError: sp=00000000 ip=4 list=028E0010)
	stack temp[4]: nil

{009308AC: cf 0093088D, sp 009308C0, bp 009308A8, ip 6, GPFault(Exception)>>_propagate}
	receiver: a GPFault
	stack temp[0]: nil

{0093088C: cf 00930871, sp 009308A0, bp 0093088C, ip 13, GPFault(Exception)>>signal}
	receiver: a GPFault

{00930870: cf 0093084D, sp 00930884, bp 00930868, ip 8, GPFault class(Win32Fault class)>>signal:with:}
	receiver: GPFault
	arg[0]: nil
	arg[1]: a EXCEPTION_RECORD

{0093084C: cf 0093082D, sp 00930860, bp 00930848, ip 5, GPFault class(Exception class)>>signalWith:}
	receiver: GPFault
	arg[0]: a EXCEPTION_RECORD

{0093082C: cf 00930809, sp 00930840, bp 00930824, ip 10, ProcessorScheduler>>gpFault:}
	receiver: a ProcessorScheduler
	arg[0]: a ByteArray
	stack temp[0]: a EXCEPTION_RECORD

{00930808: cf 009307DD, sp 0093081C, bp 00930800, ip 16, [] in ProcessorScheduler>>vmi:list:no:with:}
	receiver: a ProcessorScheduler

{009307DC: cf 009307BD, sp 009307F0, bp 009307D8, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 24 in ProcessorScheduler>>vmi:list:no:with:

{009307BC: cf 00930791, sp 009307D0, bp 009307AC, ip 27, ProcessorScheduler>>vmi:list:no:with:}
	receiver: a ProcessorScheduler
	arg[0]: 1408
	arg[1]: nil
	arg[2]: 5
	arg[3]: a ByteArray

{00930790: cf 00930765, sp 009307A4, bp 00930780, ip 0, ScintillaLibrary>>directFunction:msg:wParam:lpParam:}
	receiver: a ScintillaLibrary
	arg[0]: a ExternalHandle(21B16B10)
	arg[1]: 2200
	arg[2]: 2767
	arg[3]: nil

{00930764: cf 00930741, sp 00930778, bp 0093075C, ip 17, ScintillaView>>sciCallTipShow:definition:}
	receiver: a ScintillaView
	arg[0]: 2768
	arg[1]: nil

{00930740: cf 0093071D, sp 00930754, bp 00930738, ip 4, ScintillaView>>showCallTip:at:}
	receiver: a ScintillaView
	arg[0]: nil
	arg[1]: 2768

{0093071C: cf 009306F5, sp 00930730, bp 00930710, ip 42, JadeAutoSystemBrowserPresenter(JadeSystemBrowserPresenter)>>methodHoverStart:}
	receiver: a JadeAutoSystemBrowserPresenter
	arg[0]: a Point
	stack temp[0]: 2768
	stack temp[1]: a ScintillaIndicator

{009306F4: cf 009306D1, sp 00930708, bp 009306EC, ip 13, EventMessageSend>>forwardTo:withArguments:}
	receiver: a EventMessageSend
	arg[0]: a JadeAutoSystemBrowserPresenter
	arg[1]: a Array

{009306D0: cf 009306B1, sp 009306E4, bp 009306CC, ip 5, EventMessageSend(MessageSendAbstract)>>valueWithArguments:}
	receiver: a EventMessageSend
	arg[0]: a Array

{009306B0: cf 00930685, sp 009306C4, bp 009306A8, ip 12, [] in MessageSequenceAbstract>>valueWithArguments:}
	receiver: nil
	arg[0]: a EventMessageSend

{00930684: cf 00930655, sp 009306A0, bp 00930670, ip 30, EventMessageSequence>>messagesDo:}
	receiver: a EventMessageSequence
	arg[0]: [] @ 9 in MessageSequenceAbstract>>valueWithArguments:
	stack temp[0]: a DeadObject
	stack temp[1]: 1
	stack temp[2]: a JadeAutoSystemBrowserPresenter
	stack temp[3]: a EventMessageSend

{00930654: cf 00930635, sp 00930668, bp 00930650, ip 16, EventMessageSequence(MessageSequenceAbstract)>>valueWithArguments:}
	receiver: a EventMessageSequence
	arg[0]: a Array
	env temp[0]: nil

{00930634: cf 00930611, sp 00930648, bp 0093062C, ip 14, EventsCollection>>triggerEvent:with:}
	receiver: a EventsCollection
	arg[0]: hoverStart:
	arg[1]: a Point

{00930610: cf 009305ED, sp 00930624, bp 00930608, ip 5, JadeAutoTextPresenter3(Object)>>trigger:with:}
	receiver: a JadeAutoTextPresenter3
	arg[0]: hoverStart:
	arg[1]: a Point

{009305EC: cf 009305C9, sp 00930600, bp 009305E4, ip 9, ScintillaView>>scnDwellStart:}
	receiver: a ScintillaView
	arg[0]: a ExternalAddress
	stack temp[0]: a SCNotification

{009305C8: cf 009305A5, sp 009305DC, bp 009305C0, ip 18, ScintillaView>>nmNotify:}
	receiver: a ScintillaView
	arg[0]: a ExternalAddress
	stack temp[0]: scnDwellStart:

{009305A4: cf 00930575, sp 009305B8, bp 00930590, ip 18, CardContainer(View)>>wmNotify:wParam:lParam:}
	receiver: a CardContainer
	arg[0]: 78
	arg[1]: 4385
	arg[2]: 1701432
	stack temp[0]: a ExternalAddress
	stack temp[1]: a ScintillaView

{00930574: cf 00930545, sp 00930588, bp 00930560, ip 23, CardContainer(View)>>dispatchMessage:wParam:lParam:}
	receiver: a CardContainer
	arg[0]: 78
	arg[1]: 4385
	arg[2]: 1701432
	stack temp[0]: nil
	stack temp[1]: wmNotify:wParam:lParam:

{00930544: cf 00930511, sp 00930558, bp 00930534, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{00930510: cf 009304E9, sp 00930524, bp 0093050C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{009304E8: cf 0093049D, sp 00930504, bp 009304D0, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 68052
	arg[1]: 78
	arg[2]: 4385
	arg[3]: 1701432
	arg[4]: 850396
	stack temp[0]: a CardContainer

{0093049C: cf 00930475, sp 009304C8, bp 00930490, ip 10, ScintillaView(ControlView)>>defaultWindowProcessing:wParam:lParam:}
	receiver: a ScintillaView
	arg[0]: 275
	arg[1]: 6
	arg[2]: 0

{00930474: cf 00930445, sp 00930488, bp 00930460, ip 58, ScintillaView(View)>>dispatchMessage:wParam:lParam:}
	receiver: a ScintillaView
	arg[0]: 275
	arg[1]: 6
	arg[2]: 0
	stack temp[0]: nil
	stack temp[1]: wmTimer:wParam:lParam:

{00930444: cf 00930411, sp 00930458, bp 00930434, ip 69, [] in InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: nil

{00930410: cf 009303E9, sp 00930424, bp 0093040C, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 79 in InputState>>wndProc:message:wParam:lParam:cookie:

{009303E8: cf 009303AD, sp 00930404, bp 009303D0, ip 84, InputState>>wndProc:message:wParam:lParam:cookie:}
	receiver: a InputState
	arg[0]: 68080
	arg[1]: 275
	arg[2]: 6
	arg[3]: 0
	arg[4]: 851154
	stack temp[0]: a ScintillaView

{009303AC: cf 0093038D, sp 009303C8, bp 009303A8, ip 28, InputState>>pumpMessage:}
	receiver: a InputState
	arg[0]: a MSG

{0093038C: cf 00930361, sp 009303A0, bp 0093037C, ip 18, InputState>>loopWhile:}
	receiver: a InputState
	arg[0]: [] @ 9 in InputState>>mainLoop
	stack temp[0]: a MSG
	stack temp[1]: true
	stack temp[2]: nil

{00930360: cf 00930345, sp 00930374, bp 00930360, ip 15, InputState>>mainLoop}
	receiver: a InputState

{00930344: cf 00930329, sp 00930358, bp 00930344, ip 14, [] in InputState>>forkMain}
	receiver: a InputState

{00930328: cf 0093030D, sp 0093033C, bp 00930328, ip 13, ExceptionHandler(ExceptionHandlerAbstract)>>markAndTry}
	receiver: a ExceptionHandler

{0093030C: cf 009302E5, sp 00930320, bp 00930308, ip 22, [] in ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler

{009302E4: cf 009302C5, sp 009302F8, bp 009302E0, ip 18, BlockClosure>>ifCurtailed:}
	receiver: [] @ 0 in nil
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:

{009302C4: cf 009302A1, sp 009302D8, bp 009302BC, ip 3, BlockClosure>>ensure:}
	receiver: [] @ 17 in ExceptionHandlerAbstract>>try:
	arg[0]: [] @ 39 in ExceptionHandlerAbstract>>try:
	stack temp[0]: nil

{009302A0: cf 00930279, sp 009302B4, bp 00930294, ip 44, ExceptionHandler(ExceptionHandlerAbstract)>>try:}
	receiver: a ExceptionHandler
	arg[0]: [] @ 10 in InputState>>forkMain
	stack temp[0]: nil
	stack temp[1]: a Process('Main' base 00930000* in SessionManager>>logError: sp=00000000 ip=4 list=028E0010)
	env temp[0]: nil

{00930278: cf 00930255, sp 0093028C, bp 00930270, ip 7, BlockClosure>>on:do:}
	receiver: [] @ 10 in InputState>>forkMain
	arg[0]: ProcessTermination
	arg[1]: [] @ 13 in BlockClosure>>newProcess

{00930254: cf 00000001, sp 00930268, bp 00930254, ip 17, [] in BlockClosure>>newProcess}
	receiver: [] @ 10 in InputState>>forkMain

<Bottom of stack>

***** End of dump *****

**Comment by brunobuzzi** [comment] 2018-07-19 15:09
Are you using Jade.exe or Jade Development environment ?
If the later then do you have the latest Dolphin version ?
I have GS 3.4.1 and latest Jade and i can no reproduce that.

**Comment by obi068** [comment] 2018-07-19 18:36
Only the executable.
GS 3.4.0.
It doesn't happen very often, in the most recent versions,

**Comment by jgfoster** [comment] 2018-07-24 20:47
It appears that the problem is at JadeSystemBrowserPresenter>>methodHoverStart: when the indicator tag is nil. It seems that #updateMethodStepPoints sets a string value for each indicator's tag, but obviously something is going wrong. In any case, ignoring indicators without a tag is certainly better than the existing error.

**Comment by jgfoster** [comment] 2018-07-24 21:19
Reproducible case: double-click on a temporary variable so that it is selected and so that other references to the variable have the secondary select highlighting. Then hover over one of the other references to the variable.

**Comment by jgfoster** [comment] 2018-07-26 21:50
Fixed by 0af344b25645931c1a8260a5388f150d08706302.

**Closed as completed by jgfoster** 2018-07-26 21:50 UTC
