### ISSUE TITLE
Login to 3.4.0 failed

### ISSUE THREAD

**Issue by obi068** [jgfoster/Jade.bak#118] opened 2017-12-28 19:00 UTC
Can not login to 3.4.0 database

netldi.log

Server socket gs64ldi (protocol TCP) is created, with a delay of 30 seconds.
Summary of netldi parameters:
   The host name is 'rimo-dev'.
 GEMSTONE is: '/opt/gemstone/product'.
 GEMSTONE_NRS_ALL is: '#dir:/opt/gemstone/log'.
   Clients are not authenticated.
   Process creation MUST be through services.dat.
   Created processes belong to the account named 'gemstone'.
   The command line is:
     /opt/gemstone/GemStone64Bit3.4.0-x86_64.Linux/sys/netldid -g -n -agemstone \
      -P50377 -l /opt/gemstone/log/startnetldi.log gs64ldi
Entering Service Loop
accept failed, SSL mismatch: we expect SSL, peer does not expect SSL; client may be using old version of libgci library
accept failed, SSL mismatch: we expect SSL, peer does not expect SSL; client may be using old version of libgci library

**Comment by jgfoster** [comment] 2017-12-28 22:06
As described in the error message, this typically indicates a problem with the GCI library version. One simple explanation is that you had 3.3.6 (or something else) selected in the login window drop-down when you attempted to log in to a 3.4 repository. I suspect that the problem is a bit more subtle. My guess is that you are using an earlier version of Jade that has a pre-release version of the 3.4 GCI library (we use Jade in-house while the server version is being developed, so I end up publishing Jade with otherwise "unreleased" code; we have 3.5 in the latest!). When you then used an older version of Jade (previous to November 27), you got an earlier version of the 3.4 libraries. If you upgrade to the latest Jade (2.1.16) then I believe you will not have this problem. Let me know what version of Jade you were using when you observed the problem.

**Comment by obi068** [comment] 2017-12-29 08:17
No, i use the most recent version 2.1.16.
And the correct library version is also selected, and i was able to connect to a 3.3.3 db
on the same host with the same jade version.
This is really a blocking point in my way to upgrade to 3.4.0.

**Comment by obi068** [comment] 2017-12-29 09:33
![image](https://user-images.githubusercontent.com/1876280/34434040-ad827d94-ec83-11e7-89d1-1cf84f8c7ac3.png)

**Comment by obi068** [comment] 2017-12-29 17:43
I always get this error in the netldi log.
sslAccept failed (expected for remote gslist)
Error from SSL: error:1408F10B:SSL routines:ssl3_get_record:wrong version number:ssl/record/ssl3_record.c:252:

**Comment by jgfoster** [comment] 2017-12-29 17:57
In addition to the latest version of Jade (2.1.16) I also need to confirm that you have the GCI library DLL that came with that EXE. Please look at the bin directory and let me know the dates and sizes for libgcirpc-3.4.0-32.dll and libssl-3.4.0-32.dll. 
![screen shot 2017-12-29 at 9 55 40 am](https://user-images.githubusercontent.com/1577872/34443808-787d6e06-ec7e-11e7-9252-e491537d3e20.png)

**Comment by obi068** [comment] 2017-12-29 18:04
![image](https://user-images.githubusercontent.com/1876280/34443992-22c9ed70-eccb-11e7-83fb-56045d4bdfa9.png)

**Comment by obi068** [comment] 2017-12-29 18:06
![image](https://user-images.githubusercontent.com/1876280/34444031-6b9b9b34-eccb-11e7-865e-b99060889a39.png)

**Comment by jgfoster** [comment] 2017-12-29 18:21
Well, that does look good so far (thanks for your patience as I eliminate the obvious problems). Next I'd like to try to eliminate Jade as a factor in the problem since it is easier to push things into the "official" channels if we use the "official" products. Download the Windows client library from https://downloads.gemtalksystems.com/pub/GemStone64/3.4.0/GemStone64BitClient3.4.0-x86.Windows_NT.zip (link is at https://gemtalksystems.com/products/gs64/), unzip it into a temp directory without any spaces in the path, and try logging in using Topaz (adjusting your 'gems' and 'gemn' parameters as appropriate:


![screen shot 2017-12-29 at 10 16 54 am](https://user-images.githubusercontent.com/1577872/34444273-c34250fc-ec81-11e7-965f-12efe78eb066.png)

**Comment by obi068** [comment] 2017-12-29 18:35
Hi James,

Well since i am running a ssh tunnel with putty to connect to our servers i
think i cant not easily try the windows topaz client.

Gerhard

**Comment by jgfoster** [comment] 2017-12-29 18:39
Also, did you quit Jade after the 3.3.3 login/logout success? One long-standing problem with GCI (in GBS on VA and VW as well) is that the library does not "unload" effectively. So, if you connect to a 3.3.x database, logout, and try to login to a 3.4.x database, then the 3.3.x libraries will still be loaded and the attempt to load the 3.4.0 library will be ineffective (it will silently fail). I believe I've changed Jade so that you can't change libraries after a login (to avoid this problem), but it would be something to verify. Quit Jade, verify that it is gone using the Task Manager, launch it again, and try to login.

As to the SSH tunnel with Putty, I don't understand how that affects things. Jade uses the GCI library to connect to NetLDI. Topaz uses the GCI library to connect to NetLDI. At the network level (and even at the GCI library level), the behavior of Jade and Topaz ought to be identical.

**Comment by obi068** [comment] 2017-12-29 18:45
Yes i always try to restart Jade.

[image: Inline image 1]

Not sure how i can use the netldi port with topaz, but you are rigth it
should work.

set gems !@localhost:11111!rimo gemn !@localhost:11111!gemnetobject user
DataCurator pass swordfish

This is not correct i assume.

Gerhard

**Comment by jgfoster** [comment] 2017-12-29 19:05
The Network Resource String (NRS) format is described in Appendix C of the System Administration Guide. Consider the following (unabbreviated Topaz format):

set gemstone: **stonename**
set gemnetid: !@**gemHost**#netldi:**serviceNameOrPort**#task!gemnetobject

One key thing to remember is that the stone description is _from the perspective of the gem_ which was started by the NetLDI, **not** from the perspective of the GCI client. So, your stone NRS would typically not be on another host (though I offer it on the Advanced tab of the login shell in Jade). Furthermore, you never specify a port number for the stone connection, the NetLDI gets that from other sources. So, I think your Topaz settings should be as follows:

set gemstone: rimo 
set gemnetid: !@localhost#netldi:11111#task!gemnetobject
set user DataCurator pass swordfish

**Comment by obi068** [comment] 2017-12-29 19:06
Ok i got it!

set gems !@localhost!rimo gemn !@localhost#netldi:11111!gemnetobject user
DataCurator pass

[image: Inline image 1]

Same error as using Jade!
I have already an open issue at gemtalk help request.
I assume i should continue with your helpdesk.

Thanks
Gerhard

**Comment by jgfoster** [comment] 2017-12-29 19:07
Yes, if the error reproduces in Topaz then we will close this Jade issue and return to the GemTalk help request.

**Closed as completed by jgfoster** 2017-12-29 19:07 UTC
