### ISSUE TITLE
2.0.16 - Monticello can not be stored on server directories ...

### ISSUE THREAD

**Issue by feldti** [jgfoster/Jade.bak#55] opened 2017-01-10 13:54 UTC
It seems, that the filename from the GUI dialog is NOT used while storing the package. It seems to use the latest available name - and this is always already there ...

writeStreamForFileNamed: aString onClient: onClient replace: aBoolean do: aBlock
	"dump things to an in-memory stream, then push the contents to the GsFile"
	| file stream |
	aBoolean ifFalse: [ (GsFile _exists: aString onClient: onClient) ifTrue: [self error: 'The file ', aString printString, ' already exists']].
	stream := RWBinaryOrTextStream on: String new.
	aBlock value: stream.
	file := GsFile open: aString mode: 'wb' onClient: onClient.
	aBoolean ifTrue: [ file rewind ].
	file nextPutAll: stream contents.
	file close.

**Comment by jgfoster** [comment] 2017-01-10 18:59
The method you quote appears to be in MCPlatformSupport and is in the package Monticello.v3 in the repository http://seaside.gemtalksystems.com/ss/monticello. Is that correct? Do you have problems with that method, or with code that calls that method? Where is the GUI dialog? Can you provide some steps to reproduce this, describing what actually happens and what you want to happen?

**Comment by feldti** [comment] 2017-01-11 09:03
When I tried to save a changed packages I ran into this problem. With 2.0.15 I got an error message. With 2.0.16 I got a debugger window showing me this message. With 2.0.14 I have no problems at all - therefore I stayed with 2.0.14

**Comment by jgfoster** [comment] 2017-01-12 05:38
I've been able to reproduce a problem (thought it seems to me to exist in 2.0.14) and I believe it is fixed in 2.0.17. Please let me know if things work for you now. Thanks for your help.

**Comment by feldti** [comment] 2017-01-12 06:40
Just tested with 2.0.17 and it worked

**Comment by feldti** [comment] 2017-01-12 06:49
No its still there ... but in a different kind. Do not know yet - stay with 2.0.14

**Comment by feldti** [comment] 2017-02-03 12:20
Ok, looked around it again - something is wrong there. It not always takes the version number from the GUI dialog

**Comment by jgfoster** [comment] 2017-04-14 21:27
Could you give us more details on the problem? What are the steps to reproduce this problem?

**Comment by feldti** [comment] 2017-04-15 08:13
That's difficult - but I have seen these again some days ago ... when I created a new stone and had to add new local server file directories and save changes for the first time.

It "seems", that the content of the GUI field containing the name is not always used under all circumstances (instead the original number of the package is used). I tried to change the version number and then used the mouse to to save the changes of my packages.

To get rid of this behaviour I now make a tab to the Message field and after that I save the package.

![kazam_screenshot_00000](https://cloud.githubusercontent.com/assets/24528907/25062069/cf4b140c-21c4-11e7-8dd7-277b3114c70a.png)

**Comment by jgfoster** [comment] 2017-04-16 23:43
I created a new server directory repository (for MCZ files), and was able to save existing, unmodified files to that directory with both the original name and with a modified name. As I've been unable to reproduce this I'll close it for now. It can be reopened if we can get a reproducible case.

**Closed as completed by jgfoster** 2017-04-16 23:43 UTC
