### ISSUE TITLE
class browser fails to open after forced shut down of jade vi task manager

### ISSUE THREAD

**Issue by alexkogan** [jgfoster/Jade.bak#263] opened 2020-07-16 17:11 UTC
![image](https://user-images.githubusercontent.com/1958382/87701367-b49f4480-c74c-11ea-891f-10db4343dc8c.png)

**Comment by brunobuzzi** [comment] 2020-07-16 17:22
Possible workaround (@alexkogan):
Try to delete "Jade System Browser Layout.stb" in Jade folder.
Not 100% sure if it will work but i used it a lot of times when browser does not open.

**Comment by alexkogan** [comment] 2020-07-16 17:26
Works of course. Just wanted to note a bug. Thanks!

**Comment by brunobuzzi** [comment] 2020-07-16 21:49
@alexkogan which version of Jade ?
Is this happening with Jade.exe or Jade development image ?
Because i can not reproduce the issue nor with Jade.exe not in Dolphin image

**Comment by alexkogan** [comment] 2020-07-16 21:57
It's fairly old version. I thought it was on latest but it's actually 2.3.13. It was Jade.exe

**Comment by jgfoster** [comment] 2020-08-10 17:33
Believed to be fixed by 7b9f0042788d4503d2ae0a4f2ad779ef40e85d25.

**Closed as completed by jgfoster** 2020-08-10 17:33 UTC
